### ISSUE TITLE
error when encountering makemigrations

### ISSUE THREAD

**Issue by Macadamiya** [ankitchhatbar/django-group-model#1]
hello!
I followed the steps in the documentation, but encountered some errors during makemigrateions:
SystemCheckError: System check identified some issues:

ERRORS:
accounts.User.user_permissions: (fields.E304) Reverse accessor 'Permission.user_set' for 'accounts.User.user_permissions' clashes with reverse accessor for 'auth.User.user_permissions'.
HINT: Add or change a related_name argument to the definition for 'accounts.User.user_permissions' or 'auth.User.user_permissions'.
auth.User.user_permissions: (fields.E304) Reverse accessor 'Permission.user_set' for 'auth.User.user_permissions' clashes with reverse accessor for 'accounts.User.user_permissions'.
HINT: Add or change a related_name argument to the definition for 'auth.User.user_permissions' or 'accounts.User.user_permissions'.

My models:

```
class Role(AbstractGroup):
     category = models.CharField(max_length=50)

     class Meta:
         verbose_name = "role"
         verbose_name_plural = "roles"


class User(AbstractUser):
     roles = models.ManyToManyField(
         'accounts.Role',
         blank=True,
         related_name="user_set",
         related_query_name="user",
     )
     groups = None
```

**Comment by ankitchhatbar** [comment]
Hi @Macadamiya,
From looking at the error message, it seems like you have 2 `User` models in the same project. One is `auth.User` and the other is `accounts.User`. I don't think Django supports 2 user models at the same time. You may want to have only one. 

Please let me know if this works or my assumptions are incorrect, or you run into another issue.

**Comment by Macadamiya** [comment]
Thank you, I have solved it, I rewrote a user_permissions in User and used another related_name
Thank you again for your contribution, it helps me a lot @ankitchhatbar
